api_version = "2026-01"

[[extensions]]
type = "ui_extension"
name = "t:name"
uid = "b24ef760-5cd7-4625-80d4-8395ad5b8be4"
handle = "staff-profile"
description = "Trubuild: Staff dashboard profile"

[extensions.supported_features]
runs_offline = true

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
