api_version = "2026-01"

[[extensions]]
type = "ui_extension"
name = "t:name"
uid = "5f32c9c2-f9dc-423e-8eac-1d2e6b5ebaff"
handle = "view-shifts"
description = "Trubuild: View upcoming shifts"

[extensions.supported_features]
runs_offline = true

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
