# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94ec09cf3eaee34d49da7c9a2e1b91cd"
name = "Trubuild: Staff Management"
handle = "trubuild-staff-management"
application_url = "https://staff-time.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spaceraceplayground.myshopify.com"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled", "app/scopes_update" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_orders,read_products"

[auth]
redirect_urls = [
  "https://staff-time.onrender.com/auth/callback",
  "https://staff-time.onrender.com/auth/shopify/callback",
  "https://staff-time.onrender.com/api/auth/callback"
]

[pos]
embedded = true
