name = "Trubuild: POS Staff Clock In"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"
port = 3458

[commands]
predev = "npm exec prisma generate"
dev = "npm exec prisma migrate deploy && npm exec react-router dev"
