# StaffTime — Workforce OS for Shopify POS
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94ec09cf3eaee34d49da7c9a2e1b91cd"
name = "StaffTime"
application_url = "https://largely-main-ringtail.ngrok-free.app"
embedded = true

[access_scopes]
scopes = "read_locations,read_orders"

[auth]
redirect_urls = [
  "https://largely-main-ringtail.ngrok-free.app/auth/callback",
  "https://largely-main-ringtail.ngrok-free.app/auth/shopify/callback",
  "https://largely-main-ringtail.ngrok-free.app/api/auth/callback",
]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spaceraceplayground.myshopify.com"
