api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Workforce Clock"
handle = "workforce-clock"
uid = "b9d4c7ed-3d7c-47ee-92dc-66c60d6152a6"
description = "Trubuild: Clock in/out"

[extensions.supported_features]
runs_offline = true

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
