-- AlterTable
ALTER TABLE "Shop" ADD COLUMN "planHandle" TEXT NOT NULL DEFAULT 'free';
ALTER TABLE "Shop" ADD COLUMN "billingInterval" TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE "Shop" ADD COLUMN "staffLimit" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Shop" ADD COLUMN "subscriptionStatus" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Shop" ADD COLUMN "trialEndsAt" DATETIME;
ALTER TABLE "Shop" ADD COLUMN "shopifyShopGid" TEXT;
ALTER TABLE "Shop" ADD COLUMN "reportedStaffUsage" INTEGER NOT NULL DEFAULT 0;
