api_version = "2026-01"

[[extensions]]
type = "ui_extension"
name = "t:name"
uid = "f387a9fb-0f04-4d29-8bc2-fcb7ed806308"
handle = "view-tasklists"
description = "Trubuild: View assigned task lists"

[extensions.supported_features]
runs_offline = true

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
